/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_6 (
    input [5:0] alufn,
    input [0:0] zin,
    input [0:0] vin,
    input [0:0] nin,
    output reg [7:0] out
  );
  
  
  
  reg [0:0] muxin1;
  
  reg [0:0] muxin2;
  
  reg [0:0] muxin3;
  
  reg [2:0] muxinall;
  
  reg [7:0] preout;
  
  always @* begin
    muxin1 = zin;
    muxin2 = vin ^ nin;
    muxin3 = zin | muxin2;
    muxinall = {muxin3, muxin2, muxin1};
    preout = muxinall[((alufn[1+1-:2] - 1'h1))*1+0-:1];
    out = preout;
  end
endmodule
