/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module division_8 (
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] out
  );
  
  
  
  reg [7:0] q;
  
  reg [7:0] r;
  
  integer i;
  
  always @* begin
    q = 8'h00;
    r = 8'h00;
    for (i = 3'h7; i >= 0; i = i - 1) begin
      r = r << 1'h1;
      r[0+0-:1] = a[(i)*1+0-:1];
      if (r >= b) begin
        r = r - b;
        q[(i)*1+0-:1] = 1'h1;
      end
      out = q;
    end
  end
endmodule
