/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_5 (
    input [7:0] a,
    input [7:0] b,
    input [7:0] alufn,
    output reg [7:0] out
  );
  
  
  
  reg [2:0] shiftvalue;
  
  reg [7:0] preout;
  
  always @* begin
    shiftvalue = b[0+2-:3];
    
    case (alufn[0+1-:2])
      2'h0: begin
        preout = a << shiftvalue;
      end
      2'h1: begin
        preout = a >> shiftvalue;
      end
      2'h3: begin
        preout = $signed(a) >>> shiftvalue;
      end
      default: begin
        preout = 8'bxxxxxxxx;
      end
    endcase
    out = preout;
  end
endmodule
